[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[dependencies]
chainlink-contracts = "smartcontractkit/chainlink-brownie-contracts@v1.2.0"
openzeppelin-contracts = "OpenZeppelin/openzeppelin-contracts@v5.0.0"

# BSC Mainnet Configuration
[rpc_endpoints]
bsc = "https://bsc-dataseed.bnbchain.org"
bsc_testnet = "https://bsc-testnet-dataseed.bnbchain.org"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain = 56 }
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api", chain = 97 }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


