[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[dependencies]
chainlink-contracts = { git = "https://github.com/smartcontractkit/chainlink-brownie-contracts", tag = "v1.2.0" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.0.0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options